import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Equity Research Management — Purple8 Hyper Graph",
  description:
    "Purple8 replaces the fragmented sell-side research stack — market data ingestion, version-controlled authoring, HITL approval, event-driven publishing, and semantic client search — with a single in-process backend and a complete, queryable audit trail.",
  path: "/products/purple8/equity-research-management",
});

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Equity Research Management — Purple8 Hyper Graph",
  description:
    "Research workflows break down because approval, data lineage, and audit live in separate systems. Purple8 replaces the fragmented stack with a single in-process backend: market data ingestion, version-controlled authoring, HITL approval, event-driven publishing, and semantic client search — with a complete, queryable audit trail.",
  url: "https://www.purple8.ai/products/purple8/equity-research-management/",
  publisher: { "@type": "Organization", name: "Purple8 Inc.", url: "https://www.purple8.ai" },
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://www.purple8.ai/" },
      { "@type": "ListItem", position: 2, name: "Purple8 Hyper Graph", item: "https://www.purple8.ai/products/purple8/" },
      { "@type": "ListItem", position: 3, name: "Equity Research Management", item: "https://www.purple8.ai/products/purple8/equity-research-management/" },
    ],
  },
  mainEntity: {
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "Can Purple8 replace our existing research management system?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. Purple8 can replace the entire stack — authoring, approval workflow, data lineage, publishing, and client portal — or be deployed as the workflow and audit layer alongside existing tools. Most firms start with approval workflow and audit trail because that is where the most compliance risk is concentrated.",
        },
      },
      {
        "@type": "Question",
        name: "How does Purple8 handle MiFID II and SEC research disclosure requirements?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Every workflow step is recorded as an immutable graph edge: who authored, who reviewed, who approved, and what data supported the recommendation. The audit trail is built into the platform — it cannot drift from reality because it is generated by the system, not maintained separately. MiFID II inducement records, conflict-of-interest disclosures, and fair and clear communication checks are modelled as mandatory HITL gates in the Journey Engine workflow.",
        },
      },
      {
        "@type": "Question",
        name: "How does the market data lineage work?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Data files dropped into a watched folder — or pushed via API from a Bloomberg SFTP or Refinitiv feed — are ingested automatically. Every data point is stored with the exact timestamp it was sourced. When a recommendation is published, each cited figure carries a permanent link to the source snapshot. A compliance query — 'what data supported this price target on this date?' — is answered in seconds.",
        },
      },
      {
        "@type": "Question",
        name: "How does the semantic client portal work for entitlement enforcement?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Clients search by meaning, not keywords. The vector search layer finds reports semantically related to their query even when exact terms don't appear. Entitlement is enforced at the search layer itself — a client's subscription tier, geography, and asset class permissions are graph properties that filter every search result before it is returned. There is no separate access control list to maintain.",
        },
      },
      {
        "@type": "Question",
        name: "What happens when a report needs to be retracted?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Retraction is a single operation. Purple8 marks the report as retracted, publishes a correction to every delivery channel simultaneously, and logs the full retraction record — who initiated it, when, and why — as a permanent graph event. The original publication history is preserved. There is no manual outreach to individual recipients.",
        },
      },
    ],
  },
};

const pillars = [
  {
    number: "01",
    icon: "📡",
    title: "Market Data Ingestion & Lineage",
    subtitle: "Data Provenance · Regulatory Defensibility",
    desc: "Data files are ingested automatically from watched folders or pushed via API from Bloomberg SFTP, Refinitiv, or any structured feed. Every data point is stored with a timestamp and linked permanently to any report that cites it. When a regulator asks which close price or earnings estimate supported a recommendation, the answer is a single graph query — not a search through analyst files.",
    tags: ["Automatic ingestion", "Timestamp provenance", "Data-to-recommendation links", "Snapshot retrieval"],
  },
  {
    number: "02",
    icon: "✍️",
    title: "Version-Controlled Authoring",
    subtitle: "Draft Management · No Shared Drives",
    desc: "Every document save creates a new version linked to the one it replaces. The current authoritative version is always unambiguous. Previous drafts are preserved and queryable. There is no Review_v3 vs Final_FINAL ambiguity — the graph knows the history of every document from first keystroke to publication.",
    tags: ["Immutable version chain", "Authoritative version", "Full draft history", "Concurrent edit handling"],
  },
  {
    number: "03",
    icon: "✅",
    title: "HITL Approval Workflow",
    subtitle: "Compliance · Supervisor Sign-Off · Audit",
    desc: "Routing rules — who reviews what, by sector, asset class, or conflict flag — are configured once in the workflow definition. Deadlines are enforced automatically: if a review is not completed in time, the platform escalates and records the breach. Every approval, rejection, and comment is a permanent graph edge. When a reviewer leaves the firm, the decision record stays.",
    tags: ["Configurable routing", "SLA enforcement", "Escalation", "Immutable decision record", "Conflict flags"],
  },
  {
    number: "04",
    icon: "📤",
    title: "Event-Driven Publishing",
    subtitle: "Distribution · Delivery Logging · Retraction",
    desc: "The moment a report is approved, it publishes simultaneously to every configured channel — email, client portal, Bloomberg terminal, and any other integration. Every delivery is logged individually: who received it, when, and on which channel. Retraction is a single operation that records the correction and preserves the full publication history. No manual outreach. No duplicate sends.",
    tags: ["Approval-triggered publish", "Per-delivery logging", "One-click retraction", "Multi-channel distribution"],
  },
  {
    number: "05",
    icon: "🔎",
    title: "Semantic Client Research Portal",
    subtitle: "Vector Search · Entitlement Enforcement",
    desc: "Clients search by meaning, not keywords. A query about 'European bank capital concerns' finds relevant reports even when those exact words don't appear. Related coverage, superseded ratings, and linked issuers surface automatically. Entitlement is enforced at the search layer — subscription tier, geography, and asset class permissions are graph properties that filter every result before it is returned. Clients are notified in real time when a followed report is published.",
    tags: ["Semantic vector search", "Relationship surfacing", "Entitlement at search layer", "Real-time notifications"],
  },
  {
    number: "06",
    icon: "🗂️",
    title: "Unified Audit Trail",
    subtitle: "Compliance · MiFID II · SEC Disclosure",
    desc: "The audit trail is not a log you maintain — it is the platform itself. Every action from data ingestion to client delivery is recorded as a timestamped, immutable graph event. MiFID II inducement records, conflict-of-interest disclosures, and fair and clear communication checks are mandatory HITL gates, not manual attestations. The answer to any regulator question is a graph query against the production database.",
    tags: ["Immutable event graph", "MiFID II gates", "Conflict disclosure", "Regulator-ready queries"],
  },
];

const comparison = [
  {
    item: "Data provenance",
    legacy: "Analyst manually exports XLSX — no link to the report that cites it",
    purple8: "Every cited figure carries a permanent timestamp and a link to the source snapshot",
  },
  {
    item: "Draft management",
    legacy: "Shared drives — no authoritative version, Final_FINAL ambiguity",
    purple8: "Every save is a version linked to the previous one — current version is always unambiguous",
  },
  {
    item: "Approval record",
    legacy: "Email chains — decision record leaves when the reviewer does",
    purple8: "Every approval is a permanent, searchable graph edge with full context",
  },
  {
    item: "Publishing",
    legacy: "Manual PDF distribution — no delivery log, retraction requires outreach",
    purple8: "Approval triggers publish. Every delivery logged. Retraction is one operation.",
  },
  {
    item: "Client access",
    legacy: "Keyword search — related coverage and superseded ratings never surface together",
    purple8: "Semantic search across all reports, ratings, and linked issuers — entitlement enforced at query time",
  },
  {
    item: "Compliance log",
    legacy: "Spreadsheet maintained manually — drifts from reality over time",
    purple8: "The audit trail is the platform — it cannot drift because nothing is maintained separately",
  },
];

const workflow = [
  { stage: "Draft", tag: "Each save versioned\nprevious drafts preserved", type: "auto" },
  { stage: "Submitted", tag: "Locked for review\ntimer starts", type: "auto" },
  { stage: "Compliance review", tag: "Human gate\ndeadline enforced", type: "hitl" },
  { stage: "Supervisor sign-off", tag: "Human gate\ndeadline enforced", type: "hitl" },
  { stage: "Approved", tag: "Decision recorded\npermanently", type: "done" },
  { stage: "Published", tag: "Distribution triggers\nautomatically", type: "done" },
];

const targetCustomers = [
  {
    icon: "📊",
    title: "Sell-Side Research Desks",
    desc: "Replace the fragmented research stack — authoring, approval, publishing, and client portal — or deploy Purple8 as the workflow and audit layer on top of existing tools. The entry point is wherever compliance risk is highest.",
  },
  {
    icon: "⚖️",
    title: "Compliance & Legal Teams",
    desc: "MiFID II, SEC disclosure, and FINRA research rules require an auditable record of who approved what and what data supported it. Purple8 makes that record structural — it is generated by the platform, not maintained separately.",
  },
  {
    icon: "💼",
    title: "Research Technology Owners",
    desc: "Today you maintain webhooks, ETL jobs, and connectors between tools that were never designed to talk to each other. Purple8 is one service to deploy, monitor, and debug. When something breaks at 2am, you are not tracing a failure across six systems.",
  },
  {
    icon: "🏦",
    title: "Investment Banks & Brokerages",
    desc: "Full-service research management from data ingestion to client delivery. The same graph that traces data lineage in equity research enforces entitlement in the client portal and records the audit trail for regulators.",
  },
  {
    icon: "📡",
    title: "Independent Research Providers",
    desc: "Smaller teams with fewer resources to maintain infrastructure. Purple8 ships as a single embedded backend with zero external dependencies — no separate database, no search index, no workflow engine to operate.",
  },
  {
    icon: "🔧",
    title: "Research Platform Vendors",
    desc: "Embed Purple8 as the backend of your research management product. Replace the workflow, storage, search, and audit layers with a single graph engine. Your clients get a defensible audit trail and semantic search. You get a technical moat.",
  },
];

export default function EquityResearchManagementPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <Navbar />
      <main id="main-content" className="bg-[#0a0a0f] pt-16">

        {/* Breadcrumb */}
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 pt-8">
          <nav className="flex items-center gap-2 text-xs text-zinc-600">
            <Link href="/" className="hover:text-zinc-400 transition-colors">Home</Link>
            <span>/</span>
            <Link href="/products/purple8/" className="hover:text-zinc-400 transition-colors">Purple8 Hyper Graph</Link>
            <span>/</span>
            <span className="text-zinc-400">Equity Research Management</span>
          </nav>
        </div>

        {/* Hero */}
        <section className="relative overflow-hidden py-20">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -top-48 left-1/2 h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-purple-900/12 blur-3xl" />
          </div>
          <div className="relative mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-purple-700/40 bg-purple-950/40 px-4 py-1.5 text-sm font-medium text-purple-200">
              <span className="text-base">📈</span>
              Purple8 Hyper Graph · Sell-Side Research · Workflow Intelligence
            </div>
            <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
              Research workflows break down because{" "}
              <span className="bg-gradient-to-r from-purple-400 to-violet-400 bg-clip-text text-transparent">
                approval, data lineage, and audit live in separate systems.
              </span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-zinc-400">
              Purple8 replaces the fragmented stack — market data ingestion, version-controlled authoring,
              HITL approval, event-driven publishing, and semantic client search — with a single in-process
              backend and a complete, queryable audit trail.
            </p>
            <div className="mt-8 grid grid-cols-3 gap-4 max-w-lg mx-auto">
              {[
                { stat: "6→1", label: "Systems replaced" },
                { stat: "1 op", label: "To retract any report" },
                { stat: "0", label: "Separate logs to maintain" },
              ].map((s) => (
                <div key={s.label} className="rounded-xl border border-purple-900/40 bg-purple-950/20 px-4 py-4 text-center">
                  <p className="text-2xl font-bold text-purple-300">{s.stat}</p>
                  <p className="mt-1 text-xs text-zinc-500 leading-tight">{s.label}</p>
                </div>
              ))}
            </div>
            <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <a
                href="/register/"
                className="rounded-full bg-purple-600 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-purple-900/40 transition-colors hover:bg-purple-500"
              >
                Request a demo
              </a>
              <a href="/quickstart/" className="text-base font-semibold text-zinc-300 transition-colors hover:text-white">
                See the technical architecture →
              </a>
            </div>
          </div>
        </section>

        {/* The problem */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-12 lg:grid-cols-2 items-center">
              <div>
                <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">The problem</p>
                <h2 className="mt-3 text-3xl font-bold text-white">Each handoff in the research lifecycle is a control gap.</h2>
                <p className="mt-5 text-zinc-400 leading-relaxed">
                  The compliance question that no one can answer cleanly: &ldquo;Who approved this recommendation,
                  what data supported it, and was the analyst conflicted?&rdquo;
                </p>
                <p className="mt-4 text-zinc-400 leading-relaxed">
                  Each answer lives in a different system — or in someone&rsquo;s inbox. Market data enters
                  a report as a paste with no source record. Approval happens over email. The compliance log
                  is a spreadsheet that someone maintains manually, and by the time a regulator asks, it has
                  drifted from reality.
                </p>
                <p className="mt-4 text-zinc-400 leading-relaxed">
                  Purple8 is not a better workflow tool layered on top of the existing stack.
                  It replaces the stack. One in-process backend. One data store. One audit trail that is
                  generated by the platform — not maintained separately.
                </p>
              </div>
              {/* Broken pipeline illustration */}
              <div className="space-y-3">
                {[
                  { icon: "📡", stage: "Market Data", pain: "Manual XLSX export — no data lineage" },
                  { icon: "✍️", stage: "Authoring", pain: "Shared drives — no version lock" },
                  { icon: "📧", stage: "Approval", pain: "Email chains — no auditable record" },
                  { icon: "📤", stage: "Publishing", pain: "Manual distribution — no delivery record" },
                  { icon: "🔎", stage: "Client Access", pain: "Keyword search — silos never connect" },
                ].map((row) => (
                  <div key={row.stage} className="flex items-center gap-4 rounded-xl border border-red-900/30 bg-red-950/10 px-5 py-3">
                    <span className="text-xl flex-shrink-0">{row.icon}</span>
                    <div>
                      <p className="text-sm font-semibold text-white">{row.stage}</p>
                      <p className="text-xs text-red-400">{row.pain}</p>
                    </div>
                  </div>
                ))}
                <p className="text-xs text-zinc-600 pt-1">Every arrow between these stages is a control gap. Purple8 eliminates all of them.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Workflow pipeline */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">The workflow</p>
              <h2 className="mt-3 text-3xl font-bold text-white">The approval chain becomes a permanent, searchable record — automatically.</h2>
            </div>
            <div className="flex items-stretch gap-2 overflow-x-auto pb-4">
              {workflow.map((w, i) => (
                <div key={w.stage} className="flex items-center gap-2 flex-shrink-0">
                  <div className={[
                    "rounded-xl border px-4 py-5 text-center min-w-[130px]",
                    w.type === "hitl" ? "border-purple-700/50 bg-purple-950/20" :
                    w.type === "done" ? "border-emerald-700/40 bg-emerald-950/10" :
                    "border-white/8 bg-white/[0.02]",
                  ].join(" ")}>
                    <p className={[
                      "text-sm font-bold",
                      w.type === "hitl" ? "text-purple-300" :
                      w.type === "done" ? "text-emerald-300" :
                      "text-white",
                    ].join(" ")}>{w.stage}</p>
                    <p className={[
                      "mt-1.5 text-xs whitespace-pre-line leading-relaxed",
                      w.type === "hitl" ? "text-purple-400/70" :
                      w.type === "done" ? "text-emerald-400/70" :
                      "text-zinc-500",
                    ].join(" ")}>{w.tag}</p>
                    {w.type === "hitl" && (
                      <span className="mt-2 inline-block rounded-full bg-purple-900/40 border border-purple-700/40 px-2 py-0.5 text-[10px] font-semibold text-purple-300 uppercase tracking-widest">Human gate</span>
                    )}
                  </div>
                  {i < workflow.length - 1 && (
                    <span className="text-zinc-600 text-sm flex-shrink-0">→</span>
                  )}
                </div>
              ))}
            </div>
            <div className="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-3">
              {[
                { icon: "🔀", title: "Routing defined once", desc: "Who reviews what — by sector, asset class, or conflict flag — is configured in the workflow definition. No code change required when routing rules change." },
                { icon: "⏱️", title: "Deadlines enforced automatically", desc: "If a review isn't completed in time, the platform escalates and records the breach — without anyone polling a spreadsheet or sending a reminder email." },
                { icon: "🔒", title: "Every decision is permanent", desc: "Who approved, who rejected, why, and when — all recorded automatically as the workflow runs. Nothing to export, nothing to maintain. It's there when the regulator asks." },
              ].map((f) => (
                <div key={f.title} className="rounded-2xl border border-white/8 bg-white/[0.02] p-6">
                  <div className="text-2xl mb-3">{f.icon}</div>
                  <h3 className="font-semibold text-white mb-2">{f.title}</h3>
                  <p className="text-sm text-zinc-400 leading-relaxed">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Five pillars */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">Six pillars</p>
              <h2 className="mt-3 text-3xl font-bold text-white">Six problems. One platform.</h2>
              <p className="mt-4 max-w-2xl mx-auto text-zinc-400">
                Each pillar below is a capability that ships as part of Purple8 Hyper Graph — not a separate integration.
              </p>
            </div>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
              {pillars.map((p) => (
                <div key={p.number} className="rounded-2xl border border-white/8 bg-white/[0.02] p-6 hover:border-purple-700/40 transition-colors">
                  <div className="flex items-start gap-4 mb-4">
                    <span className="text-2xl">{p.icon}</span>
                    <div>
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="text-xs font-mono text-purple-700">{p.number}</span>
                        <h3 className="text-base font-semibold text-white">{p.title}</h3>
                      </div>
                      <p className="text-xs font-semibold text-purple-400 uppercase tracking-widest">{p.subtitle}</p>
                    </div>
                  </div>
                  <p className="text-sm text-zinc-400 leading-relaxed mb-4">{p.desc}</p>
                  <div className="flex flex-wrap gap-2">
                    {p.tags.map((tag) => (
                      <span key={tag} className="rounded-full bg-purple-950/50 border border-purple-900/40 px-2.5 py-0.5 text-xs text-purple-300">{tag}</span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Comparison table */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">Side by side</p>
              <h2 className="mt-3 text-3xl font-bold text-white">Fragmented stack vs. Purple8</h2>
            </div>
            <div className="overflow-x-auto rounded-2xl border border-white/8">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-white/8">
                    <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-widest text-zinc-500">Problem today</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-widest text-zinc-500">Current tool</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-widest text-purple-400">Purple8 ✦</th>
                  </tr>
                </thead>
                <tbody>
                  {comparison.map((row, i) => (
                    <tr key={row.item} className={i % 2 === 0 ? "bg-white/[0.01]" : ""}>
                      <td className="px-6 py-4 font-medium text-zinc-300">{row.item}</td>
                      <td className="px-6 py-4 text-zinc-500">{row.legacy}</td>
                      <td className="px-6 py-4 text-purple-300 font-medium">{row.purple8}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* For the tech owner */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-12 lg:grid-cols-2 items-center">
              <div>
                <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">For the person who owns the stack</p>
                <h2 className="mt-3 text-3xl font-bold text-white">You&rsquo;re maintaining six systems. You could be maintaining one.</h2>
                <p className="mt-5 text-zinc-400 leading-relaxed">
                  Today your team maintains webhooks, ETL jobs, and custom connectors between tools that were never designed
                  to talk to each other. With Purple8, everything is one system — there are no seams to break.
                </p>
              </div>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                {[
                  { icon: "🧩", title: "No integration glue", desc: "One service to deploy, monitor, and debug. No connectors to break." },
                  { icon: "📟", title: "One runbook", desc: "When something fails at 2am, it is one service, not six." },
                  { icon: "🗂️", title: "One source of truth", desc: "One data store. Consistency is structural, not enforced by convention." },
                  { icon: "📉", title: "Fewer vendors", desc: "Each tool replaced is one fewer contract, one fewer security review." },
                ].map((c) => (
                  <div key={c.title} className="rounded-xl border border-purple-900/30 bg-purple-950/10 p-5">
                    <div className="text-xl mb-2">{c.icon}</div>
                    <h3 className="text-sm font-semibold text-white mb-1">{c.title}</h3>
                    <p className="text-xs text-zinc-400 leading-relaxed">{c.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Who it's for */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">Who uses this</p>
              <h2 className="mt-3 text-3xl font-bold text-white">Built for every firm that produces or distributes research</h2>
            </div>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {targetCustomers.map((tc) => (
                <div key={tc.title} className="rounded-2xl border border-white/8 bg-white/[0.02] p-6">
                  <div className="text-3xl mb-4">{tc.icon}</div>
                  <h3 className="text-base font-semibold text-white mb-2">{tc.title}</h3>
                  <p className="text-sm text-zinc-400 leading-relaxed">{tc.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="border-t border-white/5 py-20">
          <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">FAQ</p>
              <h2 className="mt-3 text-3xl font-bold text-white">Questions from research and compliance teams</h2>
            </div>
            <div className="space-y-8">
              {(jsonLd.mainEntity as { mainEntity: { name: string; acceptedAnswer: { text: string } }[] }).mainEntity.map((faq) => (
                <div key={faq.name} className="border-b border-white/8 pb-8">
                  <h3 className="text-lg font-semibold text-white mb-2">{faq.name}</h3>
                  <p className="text-zinc-400 leading-relaxed">{faq.acceptedAnswer.text}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Related capabilities */}
        <section className="border-t border-white/5 py-16">
          <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <p className="text-xs font-semibold uppercase tracking-widest text-zinc-600 mb-6">Capabilities used in this workflow</p>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              {[
                { href: "/products/purple8/workflow-orchestration/", label: "Workflow Orchestration", desc: "HITL approval pipeline with SLA enforcement" },
                { href: "/products/purple8/rag-pipeline/", label: "GraphRAG", desc: "Semantic client portal — search by meaning, not keywords" },
                { href: "/products/purple8/agentic-process-automation/", label: "Agentic Process Automation", desc: "Data ingestion, routing, and publishing — automated" },
                { href: "/products/purple8/multi-agent-systems/", label: "Multi-Agent Systems", desc: "Parallel review coordination across sectors and asset classes" },
                { href: "/products/purple8/ma-due-diligence/", label: "DocIntel", desc: "Document intelligence for ingesting structured research inputs" },
                { href: "/products/purple8/financial-crime-intelligence/", label: "Financial Crime Intelligence", desc: "Conflict-of-interest and entitlement graph for research portals" },
              ].map((cap) => (
                <Link key={cap.href} href={cap.href} className="group rounded-xl border border-white/8 bg-white/[0.02] px-5 py-4 transition-colors hover:border-purple-700/50">
                  <p className="text-sm font-semibold text-purple-300 group-hover:text-purple-200">{cap.label} →</p>
                  <p className="mt-1 text-xs text-zinc-500">{cap.desc}</p>
                </Link>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="border-t border-white/5 py-20 text-center">
          <div className="mx-auto max-w-2xl px-4">
            <h2 className="text-3xl font-bold text-white">See a research workflow run end-to-end</h2>
            <p className="mt-4 text-zinc-400">
              The demo covers data ingestion, HITL approval, publishing, and a live semantic search query
              against a portfolio of published research — with the full audit trail queryable in real time.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <a
                href="/register/"
                className="rounded-full bg-purple-600 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-purple-900/40 transition-colors hover:bg-purple-500"
              >
                Request a demo
              </a>
              <a href="/products/purple8/" className="text-base font-semibold text-zinc-300 transition-colors hover:text-white">
                Explore Purple8 Hyper Graph →
              </a>
            </div>
          </div>
        </section>

      </main>
      <Footer />
    </>
  );
}
